<!--
This template is for use for the SOFT165 practical exercises.  
It has been generated by Dr Shirley Atkinson for the purposes of teaching.
-->
<?php
require_once 'public/header.php';

?>
<body class="bg-info">
    <div class="container-fluid col-md-6 offset-md-3">
    <div class="row">
        <div class="card mt-3">
        I am Michael Holt, I study CS at plymouth uni.
        <img src = "me.jpg" style="width:500px;height:400px;">
        </div>
    </div>
    </div>
     
 <?php include_once 'public/footer.php'; ?>
